import { CurrencyPipe, DatePipe } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormBuilder, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { catchError, forkJoin, of } from 'rxjs';
import { BadgeComponent, ButtonComponent, CardComponent, EmptyStateComponent, SkeletonComponent } from 'ui-core';
import { ApiService } from '../../core/services/api.service';

interface AdminUser { userId: string; email: string; role: string; accountStatus: string; displayName: string; createdAt?: string; }
interface AdminQuote { quoteId: string; quoteNumber: string; productCode: string; status: string; totalPremium?: number | null; }
interface AdminPolicy { policyId: string; policyNumber: string; productCode: string; status: string; totalPremium?: number | null; }
interface AdminClaim { claimId: string; claimNumber: string; status: string; estimatedLoss?: number | null; reportedDate?: string; }

@Component({
  selector: 'is-admin-workspace',
  standalone: true,
  imports: [CurrencyPipe, DatePipe, FormsModule, ReactiveFormsModule, RouterLink, BadgeComponent, ButtonComponent, CardComponent, EmptyStateComponent, SkeletonComponent],
  template: `
    <section class="enterprise-page admin-page">
      <header class="page-header"><div><p class="page-eyebrow">System administration</p><h1>Administration</h1><p class="page-description">Manage employee access and review live customer, quote, policy, claim, and vendor workspaces from one governed view.</p></div><is-button variant="secondary" size="sm" (click)="loadAll()" [disabled]="loading">{{ loading ? 'Refreshing…' : 'Refresh data' }}</is-button></header>
      @if (error) { <div class="error-banner" role="alert">{{ error }}</div> }
      @if (loading) { <div class="loading-grid" role="status" aria-live="polite"><is-skeleton variant="card" /><is-skeleton variant="card" /><is-skeleton variant="card" /></div> } @else {
        <div class="metric-grid"><article class="metric-card"><span>Employees</span><strong>{{ employeeCount }}</strong><small>Live user directory</small></article><article class="metric-card"><span>Policyholders</span><strong>{{ customerCount }}</strong><small>Registered accounts</small></article><article class="metric-card"><span>Quotes</span><strong>{{ quotes.length }}</strong><small>All lifecycle stages</small></article><article class="metric-card"><span>Policies</span><strong>{{ policies.length }}</strong><small>Issued and active records</small></article><article class="metric-card"><span>Claims</span><strong>{{ claims.length }}</strong><small>Operational records</small></article></div>
        <div class="admin-grid">
          <is-card title="Employee and customer directory" subtitle="Search and manage accounts using the live customer-party service.">
            <div class="toolbar"><input class="control" placeholder="Search name, email, or role" [(ngModel)]="userSearch" (keydown.enter)="loadUsers()" aria-label="Search user directory" /><select class="control" [(ngModel)]="roleFilter" (change)="loadUsers()" aria-label="Filter by role"><option value="">All roles</option>@for (role of roles; track role) { <option [value]="role">{{ formatRole(role) }}</option> }</select><select class="control" [(ngModel)]="statusFilter" (change)="loadUsers()" aria-label="Filter by account status"><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="SUSPENDED">Suspended</option></select><is-button variant="secondary" size="sm" (click)="loadUsers()">Search</is-button></div>
            @if (!filteredUsers.length) { <is-empty-state title="No matching accounts" description="The live customer-party service returned no accounts for these filters." icon="◎" /> } @else { <div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>@for (user of filteredUsers; track user.userId) { <tr><td><strong>{{ user.displayName || 'Unnamed account' }}</strong></td><td>{{ user.email }}</td><td>{{ formatRole(user.role) }}</td><td><is-badge [variant]="user.accountStatus === 'ACTIVE' ? 'success' : 'warning'" size="sm">{{ user.accountStatus }}</is-badge></td><td>{{ user.createdAt | date:'mediumDate' }}</td><td><button type="button" class="link-button" (click)="selectUser(user)">{{ selectedUser?.userId === user.userId ? 'Close' : 'Manage' }}</button></td></tr>@if (selectedUser?.userId === user.userId) { <tr class="action-row"><td colspan="6"><div class="inline-actions"><label>Role<select class="control compact" [value]="pendingRole" (change)="pendingRole = $any($event.target).value"><option value="">Keep current</option>@for (role of roles; track role) { <option [value]="role">{{ formatRole(role) }}</option> }</select></label><label>Status<select class="control compact" [value]="pendingStatus" (change)="pendingStatus = $any($event.target).value"><option value="">Keep current</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="SUSPENDED">Suspended</option></select></label><is-button variant="primary" size="sm" (click)="saveUserChanges(user)" [disabled]="savingUser">{{ savingUser ? 'Saving…' : 'Save changes' }}</is-button></div></td></tr> } } </tbody></table></div> }
          </is-card>
          <is-card title="Create employee account" subtitle="Create a governed staff account; customer business profiles remain a separate policyholder flow."><form [formGroup]="employeeForm" (ngSubmit)="createEmployee()" class="employee-form"><input class="control" placeholder="Display name" formControlName="displayName" /><input class="control" type="email" placeholder="Work email" formControlName="email" /><input class="control" type="password" placeholder="Temporary password" formControlName="password" /><select class="control" formControlName="role">@for (role of employeeRoles; track role) { <option [value]="role">{{ formatRole(role) }}</option> }</select><is-button variant="primary" size="sm" type="submit" [disabled]="employeeForm.invalid || savingEmployee">{{ savingEmployee ? 'Creating…' : 'Create employee' }}</is-button></form>@if (createMessage) { <p class="success-text" role="status">{{ createMessage }}</p> } @if (createError) { <p class="error-text" role="alert">{{ createError }}</p> }</is-card>
        </div>
        <div class="admin-grid records-grid"><is-card title="Quotes" subtitle="Live quote lifecycle records"><div class="record-list">@for (quote of quotes; track quote.quoteId) { <a class="record-row" [routerLink]="['/policy/quotes', quote.quoteId]"><span><strong>{{ quote.quoteNumber || 'Quote reference pending' }}</strong><small>{{ formatProduct(quote.productCode) }}</small></span><span><is-badge variant="info" size="sm">{{ quote.status }}</is-badge><small>{{ quote.totalPremium | currency:'INR':'symbol':'1.0-0' }}</small></span></a> } @empty { <is-empty-state title="No quotes" description="No quote records are currently available." icon="▤" /> }</div></is-card><is-card title="Policies" subtitle="Live policy lifecycle records"><div class="record-list">@for (policy of policies; track policy.policyId) { <a class="record-row" [routerLink]="['/policy/policies', policy.policyId]"><span><strong>{{ policy.policyNumber || 'Policy reference pending' }}</strong><small>{{ formatProduct(policy.productCode) }}</small></span><span><is-badge variant="success" size="sm">{{ policy.status }}</is-badge><small>{{ policy.totalPremium | currency:'INR':'symbol':'1.0-0' }}</small></span></a> } @empty { <is-empty-state title="No policies" description="No policy records are currently available." icon="▤" /> }</div></is-card><is-card title="Claims" subtitle="Live operational claim records"><div class="record-list">@for (claim of claims; track claim.claimId) { <a class="record-row" [routerLink]="['/claims', claim.claimId]"><span><strong>{{ claim.claimNumber || 'Claim reference pending' }}</strong><small>{{ claim.reportedDate || 'Reported date unavailable' }}</small></span><span><is-badge variant="warning" size="sm">{{ claim.status }}</is-badge><small>{{ claim.estimatedLoss | currency:'INR':'symbol':'1.0-0' }}</small></span></a> } @empty { <is-empty-state title="No claims" description="No claim records are currently available." icon="▤" /> }</div></is-card></div>
      }
    </section>
  `,
  styles: [`
    :host { display: block; } .admin-page { max-width: 1500px; } .loading-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 14px; } .metric-grid { grid-template-columns: repeat(5, minmax(0, 1fr)); } .metric-card { min-height: 112px; padding: 16px; } .metric-card span, .metric-card small { color: var(--muted); font-size: 10px; } .metric-card strong { display: block; margin: 14px 0 7px; font-size: 26px; } .admin-grid { display: grid; grid-template-columns: minmax(0, 1.65fr) minmax(300px, .8fr); gap: 16px; align-items: start; } .records-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); } .toolbar, .inline-actions { display: flex; flex-wrap: wrap; align-items: end; gap: 8px; padding-bottom: 15px; } .control { min-height: 36px; min-width: 0; flex: 1; padding: 8px 10px; border: 1px solid var(--border); border-radius: 6px; background: #fff; color: var(--ink); font-size: 11px; } .compact { min-width: 145px; } .toolbar .control { min-width: 150px; } .employee-form { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; } .employee-form .control, .employee-form is-button { width: 100%; } .employee-form is-button { grid-column: 1 / -1; } .table-wrap { overflow-x: auto; } table { width: 100%; min-width: 750px; border-collapse: collapse; font-size: 11px; } th, td { padding: 11px 9px; border-bottom: 1px solid var(--border); text-align: left; vertical-align: middle; } th { color: var(--muted); font-size: 9px; text-transform: uppercase; } td strong { color: var(--ink); } .link-button { border: 0; background: none; color: var(--claret); cursor: pointer; font-size: 11px; font-weight: 700; } .action-row td { background: var(--warm-light); } .inline-actions label { display: grid; gap: 4px; color: var(--muted); font-size: 10px; font-weight: 600; } .record-list { display: grid; } .record-row { display: flex; align-items: center; justify-content: space-between; gap: 14px; padding: 12px 0; border-bottom: 1px solid var(--border); text-decoration: none; } .record-row:last-child { border-bottom: 0; } .record-row strong { color: var(--claret); font-size: 11px; } .record-row small { display: block; margin-top: 4px; color: var(--muted); font-size: 9px; } .record-row > span:last-child { display: grid; justify-items: end; } .error-banner, .error-text { color: var(--danger); } .success-text { color: var(--success); font-size: 11px; } @media (max-width: 1100px) { .metric-grid, .records-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } .admin-grid { grid-template-columns: 1fr; } } @media (max-width: 650px) { .metric-grid, .records-grid, .employee-form { grid-template-columns: 1fr; } .employee-form is-button { grid-column: auto; } }
  `],
})
export class AdminWorkspaceComponent {
  private readonly api = inject(ApiService); private readonly fb = inject(FormBuilder);
  readonly roles = ['POLICYHOLDER', 'VENDOR_APPLICANT', 'UNDERWRITER', 'RISK_ENGINEER', 'CLAIMS_ADJUSTER', 'CLAIMS_MANAGER', 'VENDOR_MANAGER', 'SYSTEM_ADMINISTRATOR']; readonly employeeRoles = this.roles.filter((role) => !['POLICYHOLDER', 'VENDOR_APPLICANT'].includes(role));
  readonly employeeForm = this.fb.nonNullable.group({ displayName: ['', Validators.required], email: ['', [Validators.required, Validators.email]], password: ['', [Validators.required, Validators.minLength(8)]], role: ['UNDERWRITER', Validators.required] });
  users: AdminUser[] = []; quotes: AdminQuote[] = []; policies: AdminPolicy[] = []; claims: AdminClaim[] = []; loading = false; savingUser = false; savingEmployee = false; error: string | null = null; createError: string | null = null; createMessage: string | null = null; userSearch = ''; roleFilter = ''; statusFilter = ''; selectedUser: AdminUser | null = null; pendingRole = ''; pendingStatus = '';
  constructor() { this.loadAll(); }
  get filteredUsers(): AdminUser[] { const term = this.userSearch.trim().toLowerCase(); return this.users.filter((user) => !term || `${user.displayName} ${user.email} ${user.role}`.toLowerCase().includes(term)); }
  get employeeCount(): number { return this.users.filter((user) => !['POLICYHOLDER', 'VENDOR_APPLICANT'].includes(user.role.toUpperCase())).length; }
  get customerCount(): number { return this.users.filter((user) => user.role.toUpperCase() === 'POLICYHOLDER').length; }
  loadAll(): void { this.loading = true; this.error = null; forkJoin({ users: this.api.get<AdminUser[]>('/api/admin/users', { role: this.roleFilter || undefined, status: this.statusFilter || undefined, search: this.userSearch || undefined }), quotes: this.api.get<AdminQuote[]>('/api/quotes/admin').pipe(catchError(() => of([] as AdminQuote[]))), policies: this.api.get<AdminPolicy[]>('/api/policies/admin').pipe(catchError(() => of([] as AdminPolicy[]))), claims: this.api.get<AdminClaim[]>('/api/claims').pipe(catchError(() => of([] as AdminClaim[]))) }).subscribe({ next: (data) => { this.users = data.users; this.quotes = data.quotes; this.policies = data.policies; this.claims = data.claims; this.loading = false; }, error: (err) => { this.loading = false; this.error = err?.status === 403 ? 'Administrator privileges are required to view this workspace.' : 'The administrator data could not be loaded.'; } }); }
  loadUsers(): void { this.loadAll(); }
  selectUser(user: AdminUser): void { this.selectedUser = this.selectedUser?.userId === user.userId ? null : user; this.pendingRole = ''; this.pendingStatus = ''; }
  saveUserChanges(user: AdminUser): void { const updates = []; if (this.pendingRole && this.pendingRole !== user.role) updates.push(this.api.put(`/api/admin/users/${user.userId}/roles`, { role: this.pendingRole })); if (this.pendingStatus && this.pendingStatus !== user.accountStatus) updates.push(this.api.put(`/api/admin/users/${user.userId}/status`, { status: this.pendingStatus })); if (!updates.length) return; this.savingUser = true; forkJoin(updates).subscribe({ next: () => { this.savingUser = false; this.selectedUser = null; this.loadUsers(); }, error: () => { this.savingUser = false; this.error = 'The account change was not saved.'; } }); }
  createEmployee(): void { if (this.employeeForm.invalid) { this.employeeForm.markAllAsTouched(); return; } this.savingEmployee = true; this.createError = null; this.createMessage = null; this.api.post('/api/admin/users', this.employeeForm.getRawValue()).subscribe({ next: () => { this.savingEmployee = false; this.createMessage = 'Employee account created.'; this.employeeForm.reset({ displayName: '', email: '', password: '', role: 'UNDERWRITER' }); this.loadUsers(); }, error: (err) => { this.savingEmployee = false; this.createError = err?.error?.message || 'The employee account could not be created.'; } }); }
  formatRole(role: string): string { return role.replace(/_/g, ' ').toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase()); }
  formatProduct(product: string): string { return product.replace(/_/g, ' ').toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase()); }
}
