// Shared enums matching backend contracts across all services

export enum UserRole {
  POLICYHOLDER = 'POLICYHOLDER',
  UNDERWRITER = 'UNDERWRITER',
  CLAIMS_ADJUSTER = 'CLAIMS_ADJUSTER',
  VENDOR_MANAGER = 'VENDOR_MANAGER',
  SYSTEM_ADMINISTRATOR = 'SYSTEM_ADMINISTRATOR'
}

export enum ClaimStatus {
  FNOL_RECEIVED = 'FNOL_RECEIVED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  AWAITING_INFORMATION = 'AWAITING_INFORMATION',
  INVESTIGATING = 'INVESTIGATING',
  ASSESSING = 'ASSESSING',
  PENDING_DECISION = 'PENDING_DECISION',
  APPROVED_FOR_SETTLEMENT = 'APPROVED_FOR_SETTLEMENT',
  REJECTED = 'REJECTED',
  SETTLED = 'SETTLED',
  RECOVERY_OPEN = 'RECOVERY_OPEN',
  CLOSED = 'CLOSED'
}

export enum QuoteStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  TRIAGE = 'TRIAGE',
  IN_REVIEW = 'IN_REVIEW',
  NEEDS_INFORMATION = 'NEEDS_INFORMATION',
  RISK_ASSESSMENT = 'RISK_ASSESSMENT',
  QUOTED = 'QUOTED',
  ACCEPTED = 'ACCEPTED',
  BOUND = 'BOUND',
  ISSUED = 'ISSUED',
  DECLINED = 'DECLINED',
  WITHDRAWN = 'WITHDRAWN',
  EXPIRED = 'EXPIRED'
}

export enum PolicyStatus {
  PENDING_ISSUANCE = 'PENDING_ISSUANCE',
  BOUND = 'BOUND',
  IN_FORCE = 'IN_FORCE',
  CANCEL_PENDING = 'CANCEL_PENDING',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  REINSTATED = 'REINSTATED'
}

export enum VendorType {
  AUTO_REPAIR = 'AUTO_REPAIR',
  TOWING = 'TOWING',
  MEDICAL_CLINIC = 'MEDICAL_CLINIC',
  PROPERTY_RESTORATION = 'PROPERTY_RESTORATION',
  INSPECTION = 'INSPECTION',
  APPRAISAL = 'APPRAISAL',
  LEGAL = 'LEGAL',
  TEMPORARY_WORKSPACE = 'TEMPORARY_WORKSPACE',
  EQUIPMENT_RENTAL = 'EQUIPMENT_RENTAL',
  CLEANUP_REMEDIATION = 'CLEANUP_REMEDIATION',
  SECURITY = 'SECURITY',
  CONSULTING = 'CONSULTING',
  OTHER = 'OTHER'
}

export enum VendorVerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED'
}

export enum VendorActiveStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  INACTIVE = 'INACTIVE'
}

export enum AssignmentType {
  CLAIM_REPAIR = 'CLAIM_REPAIR',
  CLAIM_INSPECTION = 'CLAIM_INSPECTION',
  CLAIM_TOWING = 'CLAIM_TOWING',
  CLAIM_MEDICAL_ASSESSMENT = 'CLAIM_MEDICAL_ASSESSMENT',
  CLAIM_APPRAISAL = 'CLAIM_APPRAISAL',
  RECOVERY_REPAIR = 'RECOVERY_REPAIR',
  RECOVERY_TEMPORARY_WORKSPACE = 'RECOVERY_TEMPORARY_WORKSPACE',
  RECOVERY_EQUIPMENT_RENTAL = 'RECOVERY_EQUIPMENT_RENTAL',
  RECOVERY_CLEANUP = 'RECOVERY_CLEANUP',
  RECOVERY_SECURITY = 'RECOVERY_SECURITY',
  RECOVERY_CONSULTING = 'RECOVERY_CONSULTING',
  OTHER = 'OTHER'
}

export enum AssignmentStatus {
  PENDING = 'PENDING',
  DISPATCHED = 'DISPATCHED',
  OFFERED = 'OFFERED',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REASSIGNED = 'REASSIGNED'
}

export enum OnboardingStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED'
}

export enum RecoveryCaseStatus {
  INITIATED = 'INITIATED',
  ASSESSING_IMPACT = 'ASSESSING_IMPACT',
  PLANNING = 'PLANNING',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REOPENED = 'REOPENED'
}

export enum RecoveryPlanStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum RecoverySupportStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED'
}

export enum SupportType {
  REPAIR = 'REPAIR',
  TEMPORARY_WORKSPACE = 'TEMPORARY_WORKSPACE',
  EQUIPMENT_REPLACEMENT = 'EQUIPMENT_REPLACEMENT',
  TEMPORARY_EQUIPMENT = 'TEMPORARY_EQUIPMENT',
  SUPPLIER_ALTERNATIVE = 'SUPPLIER_ALTERNATIVE',
  UTILITY_RESTORATION = 'UTILITY_RESTORATION',
  IT_INFRASTRUCTURE = 'IT_INFRASTRUCTURE',
  CONSULTING = 'CONSULTING',
  OTHER = 'OTHER'
}

export enum SupportPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum RecoverySeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum RecoveryCaseStatus {
  INITIATED = 'INITIATED',
  ASSESSING_IMPACT = 'ASSESSING_IMPACT',
  PLANNING = 'PLANNING',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REOPENED = 'REOPENED'
}

export enum RecoveryPlanStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum RecoverySupportStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED'
}

export enum SupportType {
  REPAIR = 'REPAIR',
  TEMPORARY_WORKSPACE = 'TEMPORARY_WORKSPACE',
  EQUIPMENT_REPLACEMENT = 'EQUIPMENT_REPLACEMENT',
  TEMPORARY_EQUIPMENT = 'TEMPORARY_EQUIPMENT',
  SUPPLIER_ALTERNATIVE = 'SUPPLIER_ALTERNATIVE',
  UTILITY_RESTORATION = 'UTILITY_RESTORATION',
  IT_INFRASTRUCTURE = 'IT_INFRASTRUCTURE',
  CONSULTING = 'CONSULTING',
  OTHER = 'OTHER'
}

export enum SupportPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum RecoverySeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum DocumentType {
  POLICY_DECLARATIONS = 'POLICY_DECLARATIONS',
  POLICY_JACKET = 'POLICY_JACKET',
  ENDORSEMENT = 'ENDORSEMENT',
  RENEWAL_NOTICE = 'RENEWAL_NOTICE',
  CANCELLATION_NOTICE = 'CANCELLATION_NOTICE',
  REINSTATEMENT_NOTICE = 'REINSTATEMENT_NOTICE',
  QUOTE_LETTER = 'QUOTE_LETTER',
  BINDER = 'BINDER',
  SUBJECTIVITY_LETTER = 'SUBJECTIVITY_LETTER',
  FNOL_REPORT = 'FNOL_REPORT',
  LOSS_RUN = 'LOSS_RUN',
  ADJUSTER_REPORT = 'ADJUSTER_REPORT',
  MEDICAL_REPORT = 'MEDICAL_REPORT',
  POLICE_REPORT = 'POLICE_REPORT',
  APPRAISAL_REPORT = 'APPRAISAL_REPORT',
  ESTIMATE = 'ESTIMATE',
  INVOICE = 'INVOICE',
  RECEIPT = 'RECEIPT',
  PHOTOGRAPH = 'PHOTOGRAPH',
  VIDEO = 'VIDEO',
  AUDIO_RECORDING = 'AUDIO_RECORDING',
  CORRESPONDENCE = 'CORRESPONDENCE',
  LEGAL_DOCUMENT = 'LEGAL_DOCUMENT',
  COURT_FILING = 'COURT_FILING',
  SETTLEMENT_AGREEMENT = 'SETTLEMENT_AGREEMENT',
  RELEASE_FORM = 'RELEASE_FORM',
  RISK_ASSESSMENT_REPORT = 'RISK_ASSESSMENT_REPORT',
  LOSS_CONTROL_REPORT = 'LOSS_CONTROL_REPORT',
  INSPECTION_REPORT = 'INSPECTION_REPORT',
  ENGINEERING_REPORT = 'ENGINEERING_REPORT',
  APPRAISAL = 'APPRAISAL',
  SURVEY = 'SURVEY',
  MAP = 'MAP',
  DIAGRAM = 'DIAGRAM',
  PREMIUM_AUDIT_REPORT = 'PREMIUM_AUDIT_REPORT',
  COMMISSION_STATEMENT = 'COMMISSION_STATEMENT',
  FINANCIAL_STATEMENT = 'FINANCIAL_STATEMENT',
  TAX_DOCUMENT = 'TAX_DOCUMENT',
  PAYMENT_RECORD = 'PAYMENT_RECORD',
  REFUND_RECORD = 'REFUND_RECORD',
  VENDOR_CONTRACT = 'VENDOR_CONTRACT',
  SERVICE_AGREEMENT = 'SERVICE_AGREEMENT',
  WORK_ORDER = 'WORK_ORDER',
  WORK_COMPLETION_CERTIFICATE = 'WORK_COMPLETION_CERTIFICATE',
  LICENSE_CERTIFICATION = 'LICENSE_CERTIFICATION',
  INSURANCE_CERTIFICATE = 'INSURANCE_CERTIFICATE',
  AUDIT_REPORT = 'AUDIT_REPORT',
  COMPLIANCE_CERTIFICATE = 'COMPLIANCE_CERTIFICATE',
  REGULATORY_FILING = 'REGULATORY_FILING',
  EXAMINATION_REPORT = 'EXAMINATION_REPORT',
  ID_DOCUMENT = 'ID_DOCUMENT',
  PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS',
  BUSINESS_REGISTRATION = 'BUSINESS_REGISTRATION',
  AUTHORIZATION_LETTER = 'AUTHORIZATION_LETTER',
  POWER_OF_ATTORNEY = 'POWER_OF_ATTORNEY',
  OTHER = 'OTHER',
  UNKNOWN = 'UNKNOWN'
}

export enum NotificationType {
  QUOTE_ISSUED = 'QUOTE_ISSUED',
  QUOTE_SUBMITTED = 'QUOTE_SUBMITTED',
  QUOTE_APPROVED = 'QUOTE_APPROVED',
  QUOTE_REJECTED = 'QUOTE_REJECTED',
  POLICY_BOUND = 'POLICY_BOUND',
  POLICY_ISSUED = 'POLICY_ISSUED',
  POLICY_CANCELLED = 'POLICY_CANCELLED',
  POLICY_RENEWED = 'POLICY_RENEWED',
  FNOL_RECEIVED = 'FNOL_RECEIVED',
  CLAIM_ASSIGNED = 'CLAIM_ASSIGNED',
  CLAIM_APPROVED = 'CLAIM_APPROVED',
  CLAIM_REJECTED = 'CLAIM_REJECTED',
  CLAIM_SETTLED = 'CLAIM_SETTLED',
  CLAIM_CLOSED = 'CLAIM_CLOSED',
  VENDOR_ASSIGNMENT_CREATED = 'VENDOR_ASSIGNMENT_CREATED',
  VENDOR_ASSIGNMENT_ACCEPTED = 'VENDOR_ASSIGNMENT_ACCEPTED',
  VENDOR_ASSIGNMENT_DECLINED = 'VENDOR_ASSIGNMENT_DECLINED',
  VENDOR_ASSIGNMENT_COMPLETED = 'VENDOR_ASSIGNMENT_COMPLETED',
  VENDOR_ONBOARDING_SUBMITTED = 'VENDOR_ONBOARDING_SUBMITTED',
  VENDOR_ONBOARDING_VERIFIED = 'VENDOR_ONBOARDING_VERIFIED',
  VENDOR_ONBOARDING_REJECTED = 'VENDOR_ONBOARDING_REJECTED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_PROCESSED = 'PAYMENT_PROCESSED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_OVERDUE = 'TASK_OVERDUE',
  TASK_COMPLETED = 'TASK_COMPLETED',
  SLA_WARNING = 'SLA_WARNING',
  SLA_BREACH = 'SLA_BREACH',
  WORKFLOW_STARTED = 'WORKFLOW_STARTED',
  WORKFLOW_COMPLETED = 'WORKFLOW_COMPLETED',
  WORKFLOW_ESCALATED = 'WORKFLOW_ESCALATED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  AUDIT_EVENT_LOGGED = 'AUDIT_EVENT_LOGGED',
  GENERAL_ALERT = 'GENERAL_ALERT'
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH = 'PUSH',
  WEBHOOK = 'WEBHOOK'
}

export enum AuditActor {
  USER = 'USER',
  SYSTEM = 'SYSTEM',
  SCHEDULER = 'SCHEDULER',
  EXTERNAL = 'EXTERNAL',
  INTEGRATION = 'INTEGRATION',
  BATCH_JOB = 'BATCH_JOB',
  RULE_ENGINE = 'RULE_ENGINE',
  ML_MODEL = 'ML_MODEL'
}

export enum WorkflowStatus {
  INITIATED = 'INITIATED',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  PENDING_REVIEW = 'PENDING_REVIEW',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED'
}

export enum WorkflowTaskStatus {
  PENDING = 'PENDING',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  ESCALATED = 'ESCALATED',
  OVERDUE = 'OVERDUE'
}

export enum AuditStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}

export enum AuditActorType {
  USER = 'USER',
  SYSTEM = 'SYSTEM',
  SCHEDULER = 'SCHEDULER',
  EXTERNAL = 'EXTERNAL',
  INTEGRATION = 'INTEGRATION',
  BATCH_JOB = 'BATCH_JOB',
  RULE_ENGINE = 'RULE_ENGINE',
  ML_MODEL = 'ML_MODEL'
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  ASSIGN = 'ASSIGN',
  COMPLETE = 'COMPLETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT'
}