package com.intellisure.vendorpartnerservice.entity;

public enum AssignmentType {
    CLAIM_REPAIR,
    CLAIM_INSPECTION,
    CLAIM_TOWING,
    CLAIM_MEDICAL_ASSESSMENT,
    CLAIM_APPRAISAL,
    RECOVERY_REPAIR,
    RECOVERY_TEMPORARY_WORKSPACE,
    RECOVERY_EQUIPMENT_RENTAL,
    RECOVERY_CLEANUP,
    RECOVERY_SECURITY,
    RECOVERY_CONSULTING,
    RESTORATION,
    OTHER
}