server:
  port: 8084

spring:
  application:
    name: claims-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/claims_db
    username: root
    password:
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: VVGF9BeSRx3K2epQp4/DRnq881+8YixWG3KHI4qTl9I=

logging:
  file:
    name: logs/claims-service.log

springdoc:
  swagger-ui:
    path: /swagger-ui.html
